### ISSUE TITLE
Recommended workflow for data in a single table 

### ISSUE THREAD

**Issue by rbratslaver** [ropensci/coder#149]
Hi - thanks for developing this awesome package! I just wanted to confirm the proper usage if my data is in a single table i.e. let's say my starting point is `df`, how would I go about obtaining the same result from the readme example? Ty!

`
df<-coder::ex_icd10 %>%  
  left_join(coder::ex_people)
`

#result from readme:
`ch <- 
  categorize(
    ex_people,                  # patients of interest 
    codedata = ex_icd10,        # Medical codes from national patient register
    cc = "charlson",            # Calculate Charlson comorbidity
    id = "name", code = "icd10" # Specify column names
  )`

**Comment by rbratslaver** [comment]
Figured it out, closing.

**Comment by eribul** [comment]
Thank you very much @rbratslaver 
I am very happy to hear that you find the package to be useful!
