### ISSUE TITLE
Higher resolution version of coder logo

### ISSUE THREAD

**Issue by maelle** [ropensci/coder#150]
Hej @eribul, do you by any chance have a higher resolution of the package logo? I'd use it for the next rOpenSci newsletter. Tack!

**Comment by eribul** [comment]
Dear @maelle The original figure was made in PowerPoint and the file can be found under `misc/hex.pptx` or here: https://github.com/ropensci/coder/blob/master/misc/hex.pptx 
Perhaps you can use this file to generate a version wit the desired resolution? Or please let me know your preffered resolution and I will be happy to do it!

Sounds very nice with the newsletter! I am looking forward to that! :-)

Varsågod!
Är du svensk? :-)

**Comment by maelle** [comment]
Tack @eribul (jag är inte svensk men jar har läst mig svenska :slightly_smiling_face: )

The problem I have is that I only have LibreOffice. I tried the export options but it didn't help. I took a screenhsot and it has a higher res but it hides the URL (i.e. LibreOffice breaks the design). Could you try taking a screenshot from PowerPoint (unless PowerPoint has export options for increasing the quality of the PNG, it might)? Thanks for your patience!

![hex](https://user-images.githubusercontent.com/8360597/109137336-61b55300-7759-11eb-87a9-c877155794a0.png)

**Comment by maelle** [comment]
(I need at least 400 pixels width)

**Comment by eribul** [comment]
Hope this will work!
![hex_600px](https://user-images.githubusercontent.com/7790927/109177914-98ef2880-7788-11eb-9760-6d35be7ca596.png)

**Comment by maelle** [comment]
Perfekt! :tada: Tusen tack! :pray:
